#!/bin/sh
lock() {
    i3lock -f -n -e &
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && sleep 0.2 && systemctl suspend
        ;;
    hibernate)
        lock && sleep 0.2 && systemctl hibernate
        ;;
    hybrid-sleep)
	lock && sleep 0.2 && systemctl hybrid-sleep
	;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|hybrid-sleep|reboot|shutdown}"
        exit 2
esac

exit 0
